### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ViniciusPelatieri** [MatheusOliveira-dev/AutoFBackup#11]
### Pré-requisitos

[✅] Eu consigo reproduzir o problema.
[✅] Eu estou executando a [versão mais recente](https://github.com/MatheusOliveira-dev/AutoFBackup/releases) do AutoFBackup.
[✅] Eu realizei uma pesquisa anteriormente, visando evitar issues duplicadas.

### Descrição

Não fui capaz de realizar o backup ao conectar o AutoFBBackup com o FileZillaServer 1.9.3

### Passos para reproduzir

1. Criar o servidor do FileZilla com FileZilla Server.
2. Definir um usuário USER e uma senha PASSWD.
3. Conectar-me ao servidor utilizando FileZilla Client realizando o teste de conexão - Porta 21. (Obtive sucesso na conexão).
4. Acessar o arquivo C:\meus_bds\Base_bkp.FDB e envia-lo para o servidor na pasta /Users/Meu_Usuário/Desktop/bkp-ftp. (Obtive sucesso no upload).
5. Criar uma nova rotina para efetuar arquivos de backup de um banco de dados no AutoFBackup. 
6. Na aba Principal, definir as informações:
Servidor: 127.0.0.1
Porta: 21
Usuario: USER
Senha: PASSWD
Caminho: C:\meus_bds\Base_bkp.FDB
7. Na aba Opções - Backup, definir "Salvar Backups em: "c:\Users\Meu_Usuário\Desktop\bkp-ftp" 
8. Pressionar o botão azul para salvar a rotina.
9. Clicar com o botão direito na rotina e depois em Executar Rotina Agora

**Comportamento esperado:** 

O programa deveria realizar o backup do banco de dados indicado.

**Comportamento real:** 
O backup não é feito
E um log de erro é gerado: [X] Erro na Criação do Arquivo de Backup. As funções de Upload não serão executadas -> connection rejected by remote interface 

### Informações de Ambiente

* Versão Firebird: 2.5.9.27139 (Win 32)
* Versão do Windows: 11

**Comment by MatheusOliveira-dev** [comment]
Olá, @ViniciusPelatieri.

Se entendi bem, você definiu a porta do seu **banco de dados** como: `21`. Por isso o erro de: `connection rejected by remote interface`. Normalmente o Firebird utiliza a porta `3050`.

`21` seria a configuração de porta do seu servidor FTP que deve ser fornecido na aba de `Integrações`.

_Criar uma nova rotina para efetuar arquivos de backup de um banco de dados no AutoFBackup.
Na aba Principal, definir as informações:
Servidor: 127.0.0.1
Porta: 21 ---> **(Aqui deveria ficar como 3050, a porta padrão do Firebird)** <---
Usuario: USER ---> **(Aqui deve ficar o usuário owner do seu banco de dados, não do FTP. Normalmente é o SYSDBA**) <---
Senha: PASSWD ---> **(Aqui deve ficar a senha do seu banco de dados, não do FTP)** <---
Caminho: C:\meus_bds\Base_bkp.FDB_ ---> **(Aqui deve ficar o local onde está seu banco de dados na máquina local)** <---

**Comment by MatheusOliveira-dev** [comment]
Realize os ajustes que mencionei, teste novamente e retorne aqui o resultado, por favor.

**Comment by ViniciusPelatieri** [comment]
Após os ajustes funcionou perfeitamente. Obrigado!
