### ISSUE TITLE
configuracao do mega.nz

### ISSUE THREAD

**Issue by thiagoamaralcaragua** [MatheusOliveira-dev/AutoFBackup#3]
boa tarde, uso banco de dados firebird 3.0 e baixei seu projeto
fiz a configuração e na maquina local esta fazendo o backup certo
só que no mega nao faz o upload
no caminho coloquei backup na pasta raiz do mega mais não faz o upload como que configuro de maneira correta o mega
![Capturar](https://user-images.githubusercontent.com/119463183/222926153-d57c1386-c9be-4601-811c-82c7c4ac1f0a.PNG)

**Comment by MatheusOliveira-dev** [comment]
Ao criar a rotina de backup para esse Banco de Dados, a integração com o Mega já estava configurada e foi selecionada no ato da criação da rotina para ser utilizada? 

Por gentileza, anexe o JSON da Rotina. Ele está dentro da pasta `Rotinas` na raiz da pasta da aplicação.

Se a rotina for para um banco de dados remoto (acessível externamente), lembre-se de apagar a senha de acesso ao Banco de Dados no arquivo JSON antes de anexar aqui

**Comment by thiagoamaralcaragua** [comment]
boa tarde esse e o jeito que eu configurei o sistema

Em sáb., 4 de mar. de 2023 às 17:38, Matheus Oliveira <
***@***.***> escreveu:

**Comment by thiagoamaralcaragua** [comment]
[configuracao.docx](https://github.com/MatheusOliveira-dev/AutoFBackup/files/10889825/configuracao.docx)

{"BancoDeDados":{"Identificador":"thiago","Servidor":"192.168.100.77","Porta":"3050","Usuario":"sysdba","Senha":"masterkey","Caminho":"C:\\Sistema\\Dados\\DADOS.FDB"},"CriacaoBackup":{"Diretorio_Backup":"C:\\backup\\thiago","Frequencia":{"Tipo":"Hora","Hora":"1","Minuto":"","DiasSemana":[]},"Opcoes":{"FlagsBackup":["IgnoreLimbo","IgnoreChecksums","NoGarbageCollect"],"AplicativoPreBackup":{"Aplicativo":"","Argumentos":"","AguardaConclusao":false},"AplicativoPosBackup":{"Aplicativo":"","Argumentos":""},"ExcluirBackupsAntigosLocal":{"Ativo":false,"Dias":"0"},"ExecutaGfix":{"Ativo":false,"CaminhoGfix":"","ArgumentosGfix":"-mend -full -ignore"}}},"Integracoes":{"Notificacoes":{"Telegram":{"Ativo":false,"Envio":{"ChatIDDestino":"","Opcoes":{"ReceberLogTxt":false,"ReceberNotificacoesErros":false}}},"Email":{"Ativo":false,"Envio":{"Assunto":"","Destinatarios":"","Opcoes":{"ReceberLogTxt":false,"ReceberEmailErros":false}}}},"Uploads":{"MegaNZ":{"Ativo":true,"Envio":{"Pasta":"teste"}},"FTP":{"Ativo":false,"Envio":{"Diretorio":"","Opcoes":{"ExcluirBackupsAntigos":{"Ativo":false,"Dias":"0"}}}}}}}

**Comment by MatheusOliveira-dev** [comment]
Nessa rotina, está configurado para enviar o backup para a pasta: `teste` no Mega.NZ. 

Essa pasta `teste` realmente existe na raiz do Mega.NZ na conta informada?

**Comment by thiagoamaralcaragua** [comment]
esta sim enviei junto em anexo a configuração fotos de como que fiz  e a foto da conta do mega

**Comment by MatheusOliveira-dev** [comment]
Qual versão do AutoFBackup você está usando?

**Comment by thiagoamaralcaragua** [comment]
1.7.0.0

**Comment by MatheusOliveira-dev** [comment]
Essa pasta `teste` foi criada quando? Pelo que verifiquei, existe um delay entre a sincronização das pastas criadas recentemente por parte da biblioteca [MegaApiClient](https://github.com/gpailler/MegaApiClient/) utilizada pelo AutoFBackup.

Faça um teste, por gentileza: Tente realizar o upload do arquivo de backup em uma pasta já existente algum tempo na sua conta do Mega.NZ.

**Comment by thiagoamaralcaragua** [comment]
deu certo a pasta tinha criado hj
fiz o teste com uma pasta criado mais antiga e deu certo enviou o arquivo

**Comment by thiagoamaralcaragua** [comment]
uma outra duvida na integração com e-mail para notificação
tem campo host
vou usar e-mail do gmail , qual informação do gmail eu coloco no campo host seria o smtp.gmail.com ?

**Comment by MatheusOliveira-dev** [comment]
> uma outra duvida na integração com e-mail para notificação tem campo host vou usar e-mail do gmail , qual informação do gmail eu coloco no campo host seria o smtp.gmail.com ?

Sim, deve ser configurado como: 

`Host: smtp.gmail.com`
`Porta: 587`
`Usar SSL: Sim`

Além disso, talvez seja necessário habilitar a autenticação de dois fatores no G-mail e gerar uma senha de aplicativo para permitir que o AutoFBackup acesse sua conta do G-mail.

Note que: "Ao gerar uma senha de aplicativo para permitir que o AutoFBackup acesse sua conta do G-mail", será essa senha que você deverá informar no campo `Senha` desta tela de integrações.

Você pode fazer ambas ações mencionadas a partir da URL: https://myaccount.google.com/
