### ISSUE TITLE
Erro ao executar rotina de backup "unrecognized service parameter block"

### ISSUE THREAD

**Issue by lukian2000** [MatheusOliveira-dev/AutoFBackup#5]
### Pré-requisitos

* [X] Eu consigo reproduzir o problema.
* [X] Eu estou executando a [versão mais recente](https://github.com/MatheusOliveira-dev/AutoFBackup/releases) do AutoFBackup.
* [X] Eu realizei uma pesquisa anteriormente, visando evitar issues duplicadas.

### Descrição

Configurando conforme todo o manual e os parâmetros de envio de email e upload para o MegaNz, e funcionam perfeitamente, mas os backups não conseguem ser realizados sempre ocorrem o mesmo erro: "_unrecognized service parameter block_"

Já testei as conexões com o banco e consigo realizar o backup normal, utilizando o GBAK, e não tenho dificuldade de conexão com banco, pesquisei nos seus materiais de ajuda e não consegui entender porque esse erro na execução das rotinas de backup.

Seu produto é muito bom e se eu conseguir funcionar vou utilizar em suporte aos meus clientes de sistema com banco Firebird 2.5, 

### Passos para reproduzir

1. Configurar rotina de backup;
2. Executar qualquer rotina, o mesmo erro ocorre em vários computadores diferentes, e mesmo erro acontece;
3. Já tentei diversas configurações e o mesmo erro ocorre, como se fosse um problema de comunicação com o banco de dados;

**Comportamento esperado:** 

Que após as devidas configurações as rotinas de backup executem normalmente.

**Comportamento real: As rotinas não conseguem gerar os arquivos de backup e geram LOG de erro : unrecognized service parameter block** 

### Informações de Ambiente

* Versão Firebird: 2.5
* Versão do Windows: 10 / 11

## Informações Extras
unrecognized service parameter block
[X] Erro na Criação do Arquivo de Backup. As funções de Upload não serão executadas -> unrecognized service parameter block [29/06/2023-22:13:04]

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/138176500/d6c2a3c6-6626-4d3d-9104-d426dff124d1)

[Screenshots, logs, documentações de referência, etc]

## Possível Solução
Não tenho ideia de como resolver esse problema.

**Comment by MatheusOliveira-dev** [comment]
Qual a opção selecionada para `Componentes do Servidor`? `Binários Classic Server` ou `Binários Super Server`?

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/54098626/6ae2891c-9243-4b8b-8369-cc26afe14eb9)

Está sendo usado o `Guardian`? O Servidor Firebird está configurado como `Aplicação` ou `Serviço`?

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/54098626/254ce1d1-d7f8-4eb7-832e-49872711093d)

Se possível também anexar um arquivo de rotina `.json` que ocorre o erro. (Editar e apagar dados sensíveis, como senhas do banco de dados, senhas de upload e notificação)

**Comment by MatheusOliveira-dev** [comment]
Os arquivos de rotina `.json` ficam na raiz de onde a aplicação está, na pasta `Rotinas`.

**Comment by lukian2000** [comment]
Boa tarde Matheus!
Seguem as respostas e dados para tentarmos solucionar esse problema:

Qual a versão exata do Firebird 2.5? 2.5.x?
ISQL Version: **WI-V2.5.2.26540 Firebird 2.5**

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/138176500/abff900d-219e-42df-a89e-9657fd6afed8)

Qual a opção selecionada para Componentes do Servidor? Binários Classic Server ou Binários Super Server?
Pelo que levantei é **SuperServer**

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/138176500/6d3e0aaa-4eb8-48bc-bab5-afe19a5430de)

Removi o firebird e reinstalei a última versão compatível com meu sistema "2.5", com as seguintes configurações:

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/138176500/e3c0b1e5-4df4-40ac-8de5-58dcd8fedf7c)
![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/138176500/8be3c6e9-b53f-4a71-b782-2ca540c5a627)

_Localização de destino:
      C:\Program Files\Firebird\Firebird_2_5
Tipo de instalação:
      Instalação completa do Server e ferramentas de desenvolvimento.
Componentes seleccionados:
      Componentes do Servidor
         Binários Super Server
      Componentes do Programador e das ferramentas de administração
      Componentes do Cliente
Pasta do Menu Iniciar:
      Firebird 2.5 (x64)
Tarefas adicionais:
      Usar o Guardian para controlar o servidor?
      Executar o servidor Firebird como:
         Executar como um Serviço?
      Iniciar o Firebird automaticamente de cada vez que o sistema arranca?
      "Instalar a aplicação do Painel de Controlo?"
      Criar a biblioteca cliente como GDS32.DLL para "retro-compatibilidade"?_

Segue o conteudo do arquivo de Rotina Json, que já tentei várias rotinas e configuração mas não mudou nada, esse é o padrão:
---
{"BancoDeDados":{"Identificador":"BackupSmall-LNK","Servidor":"127.0.0.1","Porta":"3050","Usuario":"sysdba","Senha":"masterkey","Caminho":"C:\\Program Files (x86)\\BANCO DE DADOS\\SMALL.FDB"},"CriacaoBackup":{"Diretorio_Backup":"D:\\CLIENTES\\BACKUP\\Tools - Backup\\2.1.0\\Backups","Frequencia":{"Tipo":"Semanal","Hora":"10","ExecutaNaInicializacaoApp":false,"Minuto":"0","DiasSemana":["Terca-Feira"]},"Opcoes":{"FlagsBackup":["IgnoreLimbo","IgnoreChecksums","NoGarbageCollect","Compactar"],"AplicativoPreBackup":{"Aplicativo":"","Argumentos":"","AguardaConclusao":false},"AplicativoPosBackup":{"Aplicativo":"","Argumentos":""},"ExcluirBackupsAntigosLocal":{"Ativo":true,"Dias":"30"},"ExecutaGfix":{"Ativo":false,"CaminhoGfix":"","ArgumentosGfix":"-mend -full -ignore"}}},"Integracoes":{"Notificacoes":{"Telegram":{"Ativo":false,"Envio":{"ChatIDDestino":"","Opcoes":{"ReceberLogTxt":false,"ReceberNotificacoesErros":false}}},"Email":{"Ativo":false,"Envio":{"Assunto":"BackupSmall-Teste","Destinatarios":"email@gmail.com","Opcoes":{"ReceberLogTxt":true,"ReceberEmailErros":true}}}},"Uploads":{"MegaNZ":{"Ativo":false,"Envio":{"Pasta":"BackupFB"}},"FTP":{"Ativo":false,"Envio":{"Diretorio":"","Opcoes":{"ExcluirBackupsAntigos":{"Ativo":false,"Dias":"0"}}}}}}}
---

**Comment by MatheusOliveira-dev** [comment]
Me parece que há alguma incompatibilidade com versões `< 2.5.9`. Vou deixar registrado para futuras issues aqui.

Que bom que conseguiu sanar seu problema, qualquer coisa pode abrir uma nova issue.
