### ISSUE TITLE
Problema na compilação do projeto

### ISSUE THREAD

**Issue by willian-athenassistemas** [MatheusOliveira-dev/AutoFBackup#6]
Boa tarde Matheus, gostaria de contribuir com o projeto, porém estou tendo muita dificuldade com a biblioteca bunifu.
Poderia por gentileza me dar uma ajuda nessa instalação?
Também gostaria de contribuir com uma doação em R$ para incentivo do projeto.

**Comment by MatheusOliveira-dev** [comment]
Olá, @willian-athenassistemas.

Em primeiro lugar, obrigado pelo interesse tanto na contribuição do projeto quanto ao incentivo financeiro.

Quanto a biblioteca `Bunifu`, na pasta [ExtraPackages](https://github.com/MatheusOliveira-dev/AutoFBackup/tree/main/ExtraPackages) ao baixar o projeto, você pode encontrá-la. Se ela já constar como presente ao abrir o projeto no Visual Studio, exclua-a das referências. Logo na sequência, adicione-a como referência ao projeto pelo Visual Studio e mande recompilar todo os projetos. Com com isso e já deve funcionar. 
 
Caso não consiga mesmo assim, anexe as imagens de erro para vermos se não é algum detalhe extra.


Quanto a qualquer valor para incentivo: Se o seu desejo é contribuir financeiramente como forma de agradecimento ou motivação, dá uma olhada aqui, por favor: [Doações](https://github.com/MatheusOliveira-dev/AutoFBackup/blob/main/README.md#doa%C3%A7%C3%B5es). Agradeço desde já a intenção de ajudar o projeto.

**Comment by willian-athenassistemas** [comment]
Olá, bom dia!
Agradeço pelo retorno, e já vou realizar os testes.
Muito obrigado pela atenção.

**Comment by willian-athenassistemas** [comment]
Olá, bom dia @MatheusOliveira-dev!
Fiz conforme disse na resposta anterior, e mesmo assim continuou com o problema.
Em anexo, segue um print de como o projeto ficou.
![Captura de tela 2023-07-06 094251](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/25254071/3fb1fa91-2f79-4202-b738-91d3a1499472)

**Comment by MatheusOliveira-dev** [comment]
@willian-athenassistemas, me manda um "alô" lá por e-mail: `matheus.oliveira22002@gmail.com`. Não consegui simular aqui esse problema. Vamos conversar por lá e se for preciso, conecto remotamente no seu pc para acompanhar.

**Comment by MatheusOliveira-dev** [comment]
Fechado por falta de retorno. Aguardando contato por e-mail ou novo comentário na issue para reabrir.
