### ISSUE TITLE
Extensão dos arquivos de Backups

### ISSUE THREAD

**Issue by RASolucoesemTI** [MatheusOliveira-dev/AutoFBackup#7]
Olá Matheus! 
Sou Robson e estou usando AutoFBackup. 
Gostaria de saber se tem como implementar uma opção para se escolher a extensão do arquivo de Backup, pois hoje é criado como .fbk.
Teria como colocar pra gerar no formato .bck? Assim agente poderia escolher entre as duas extensões!
Estou pedindo isso porque o sistema que trabalho gera o backup com a extensão .bck.
Exemplo: **18072023_233018.bck**
Agradeço desde já!
Depois manda sua chave PIX!

**Comment by MatheusOliveira-dev** [comment]
Opa, tudo certo?

Sairá até o final da semana essa opção.

![image](https://github.com/MatheusOliveira-dev/AutoFBackup/assets/54098626/2336f530-a033-4b90-9e56-b9c99da4d86f)

Sobre a chave PIX: [Qualquer incentivo é bem-vindo](https://github.com/MatheusOliveira-dev/AutoFBackup#doa%C3%A7%C3%B5es)!

**Comment by RASolucoesemTI** [comment]
Opa meu amigo!
Vai ficar ótimo.
Estou de viagem, mas assim que chegar na minha cidade eu faço um PIX pra vc.
Deus abençoe poderosamente sua vida!

**Comment by MatheusOliveira-dev** [comment]
Por gentileza, testar na [última versão](https://github.com/MatheusOliveira-dev/AutoFBackup/releases/latest).

Pode-se atualizar o aplicativo na tela inicial dele, no botão `Atualizar App`.

Se necessário, abrir uma nova issue, por favor.
