### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by weverttec** [MatheusOliveira-dev/AutoFBackup#8]
Opa Amigo, Como faço pra enviar o backup do banco para O Mega? Não conseguir de geito nenhum, fiz alguns pix pra vc como gratidão pelo projeto.. se pode me chamar no whatsapp, 74999397404, para me ajudar fico grato e te pago por isso

**Comment by MatheusOliveira-dev** [comment]
Oi, @weverttec. Desculpe a demora pelo retorno, estava viajando.

Você segue com algum problema? 

No AutoFBackup, a única configuração necessária é a criação da integração com o: [Mega.nz](https://github.com/MatheusOliveira-dev/AutoFBackup/wiki/5.-Integrando-com-Mega.nz) e se certificar de ter habilitado o envio para o provedor na criação da rotina de backup.

**Comment by weverttec** [comment]
Fala Brother consegue falar comigo pelo whatsapp? 74999397404, quero aprimorar uma Idea no auto backup eu te pago

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
